{% set name = "pytest-env" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d7b2f5273ec6d1e221757998bc2f50d2474ed7d0b9331b92556011fadc4e9abf

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pytest >=2.6.0

test:
  imports:
    - pytest_env
  commands:
    - pytest --help

about:
  home: https://github.com/MobileDynasty/pytest-env
  license: MIT
  license_file: LICENSE
  license_family: MIT
  # license file is missing from sdist: https://github.com/MobileDynasty/pytest-env/issues/6
  summary: py.test plugin that allows you to add environment variables.

extra:
  recipe-maintainers:
    - nicoddemus
