travis:
  secure:
    BINSTAR_TOKEN: LaXJ6HLa4dEtB32S205lPRSoEt34ntF1wzzy3DO49dQm+b+vGudVZGv8ZUZMjEInCdb/5PoDyJPFrxZpzZO92AOvttcyu0R1X99837YxK/va/LQKBDZsxXcNp9/La6WgneLaitiyELK547E/mrYg4T/5tJDit3YrxN0RxiH+OVbgKKWBCqoV5E6vHutN47mwIUgl/5gQCpu48OyIIOFCjQLyl8zun5+2yAPfll/odH7gkctC+c8mxprdha7h9thvmGqOt4oOCeI5A68jZQM1ROu8/YrN003bEEOUUwyoWEMcXRYxoSzJW5jyKRIIGqQPNAYMOOc5zNSEe0B9Kx/oWoLbQ0VXjJrd9Ioc+VVZck1Ex8ZKRfOmm4f81krQcVaxNIBllG37A3r2pAYBfzzg1Kyxx+Jl/WbMJgPd8qyVm7v5sCJc7JnrJqV7URdcilJGIMQ9KXiiRU6v4ffkOXqSmw6cXaQxf5Y1FQMC/KKIUUxqP2wmmBcE0cC1iqbzhXSGEXllfGP3ISx6yyTLFGYMAh/GYVINJQubRuw7u/r+BO/tp16Z3wAelVYwW8Vy5bjG8uqO2z0/YAaiIhKAWgqNhgIFvEI67b3ZQT2EAgL2p/PLZ1wfkYPiLMTdc89mElNwTqz54gaaG3malzUEhTD5HtgA2ScIxU3EmpekJ6e8EkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
