travis:
  secure:
    BINSTAR_TOKEN: DLgSl72NBq6RbGHXh8z0BnTFABZsrNFeg3HrWmMfjCsXqc4b99FClid+3E443kjBkOkGmhhWjiSmmIo1HK5TGwYUbjCydXT1OZoqgNgNrAhsrbs5vkZ0vC9u5d1KBfgAX/ddmOmGriFD+gFdvLWI6vSiDr4O8JiJfnMhydaVeESij8IL4h7lzZ/SiyUuFIYuED5LlJpk24+DUbhbBKT94AEXt1vy18QlJBhwY0/wypA8jmm2EwvIIhvS3X7Nag+MQj5ME3hr35f+ImAok80CKerWOFT22YgzcnMKbj8zyReCrkKoVTER8z9QWvD//NnGXG+Zm6uQoo/G3fZvTbc7XlEj+vPJ10+5jEo0gkXlfixzBVnRbPA6ZUEJreB2vB1C5J1QzJXU+NnWZZT6ZUgPB2C2EnEbwTvdmkBCBFKaWL+MV0Izc3pO20sHmIBLye/LPlG9zXvwi4JAYlTqs9DYDxhJP0jrNXE3K0UBXszPghhSXUcNvKxCkXZb9mPYN/Osvx+s6GaC859JpB4fh07reRkhwyiWmySRMu0424kBT5ON9Y/M3PrmPvo4Mprw9vZDnnwKskC+bglObYaYdEKLyqxIHwH2UmY8rfH0fe5mtMxbe4KS5lmEJ1RsEbp4qDbNSznw8+TtU7HU67Y+EBrM9z0XKuYMVMf5oXUxnVaw6uM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
